### PR TITLE
ogrinfo(): make arg passing in GDALVectorInfoOptions depend on GDAL version

### PR DESCRIPTION
**Pull request by ctoney**
Still trying to get consistent behavior with GDAL 3.8 vs 3.9 beta, wrt argument passing in the `GDALVectorInfoOptions` struct. This seems related to the new `GDALArgumentParser` class in 3.9 beta.

see #322 #323

### CODE REVIEW

**Comment by ctoney** [comment]
Hi @rouault, is the text below sufficient for feedback on 3.9beta1? I can send to gdal-dev if that is preferred. I'm troubleshooting a test failure in R package `gdalraster` which provides API bindings. Thanks.

`GDALVectorInfo()` seems to exhibit different behavior in 3.9.0beta1 compared with 3.8. Code that works with 3.8 does not work with 3.9.0beta1, and I cannot figure out how to get equivalent working code with 3.9.0beta1. 

`GDALVectorInfo()` takes a `GDALDatasetH hDataset` and a `GDALVectorInfoOptions` struct. Documentation for `GDALVectorInfoOptionsNew()` says

>potentially including filename and open options too

I'm not sure why the filename is needed since we're passing the dataset (i.e., the `hDataset` opened from   `<datasource_name>`). But with GDAL 3.8, passing the  `<datasource_name>` in the arg list, right before `<layer> [<layer> ...` gives expected results.

This works with 3.8 (i.e., `GDALVectorInfo()` returns expected output):
* `hDataset` created from `<datasource_name>`
* `GDALVectorInfoOptions` created from arg list `{"-so", "-nomd", "<datasource_name>", "<layer>"}`

But with 3.9.0beta1 the same arg list gives:
`ERROR 1: filename: 0 argument(s) expected. 1 provided.` from the call to `GDALVectorInfoOptionsNew()` which then returns `nullptr`.

If we omit `<datasource_name>` in the arg list with 3.8, then `<layer>` seems to be interpreted as the `<datasource_name>` instead, and output is not as expected.

With 3.9beta1, having no dsn or layer name in the arg list works for:
* `hDataset` created from `<datasource_name>`
* `GDALVectorInfoOptions` created from arg list {"-so", "-nomd"}
which gives, for example:
```
INFO: Open of `/usr/local/lib/R/site-library/gdalraster/extdata/ynp_fires_1984_2022.gpkg'
      using driver `GPKG' successful.
1: mtbs_perims (Multi Polygon)
```

But I can't see how to pass a `<layer>` correctly in `GDALVectorInfoOptions` with 3.9beta1.

Note that a wrapper of `GDALVectorTranslate()` uses essentially the same code for arg passing, but does not seem to need ` <dst_dataset_name>` or `<src_dataset_name>` in the arg list, and `<layer>` is passed correctly in that case. Behavior with `GDALVectorTranslate()` seems to be the same with 3.8 vs 3.9beta1.

The `ogrinfo()` wrapper is at:
https://github.com/USDAForestService/gdalraster/blob/9fdf8e738eb7bc67e644871bb910dc3f6567d836/src/gdal_exp.cpp#L1378

The `ogr2ogr()` wrapper is at:
https://github.com/USDAForestService/gdalraster/blob/9fdf8e738eb7bc67e644871bb910dc3f6567d836/src/gdal_exp.cpp#L1245

**Comment by rouault** [comment]
> is the text below sufficient for feedback on 3.9beta1?

yes, thanks! This was indeed a regression that will be fixed in final 3.9.0 per https://github.com/OSGeo/gdal/pull/9763 . Obviously it showed that our regression test suite didn't check passing layer names in the context of GDALVectorInfo as a library function, which is now fixed

**Comment by rouault** [comment]
you'll note in https://github.com/OSGeo/gdal/pull/9763 that I've added a comment explaining that the dataset name in the argument list may be dummy.

**Comment by ctoney** [comment]
Nice, thanks!

Note for this current PR in gdalraster which was merged:
commit 13d5637 will be reverted in a separate PR eventually. It was an attempt at a workaround which should not be needed now (and is ineffective anyway).

**Comment by ctoney** [comment]
No errors running the test set in `gdalraster` with 3.9.0 beta2. Thanks for providing Docker images.

**Pull request merged**
