### PR TITLE
add vsi_copy_file()

### PR DESCRIPTION
**Pull request by ctoney**
This pull request adds the function `vsi_copy_file()`, a wrapper for `VSICopyFile()` in the GDAL Common Portability Library. Requires GDAL >= 3.7.

From the GDAL documentation:
>The following copies are made fully on the target server, without local download from source and upload to target:
/vsis3/ -> /vsis3/
/vsigs/ -> /vsigs/
/vsiaz/ -> /vsiaz/
/vsiadls/ -> /vsiadls/
any of the above or /vsicurl/ -> /vsiaz/ (starting with GDAL 3.8)

Note that the function `gdalraster::copyDatasetFiles()` uses `new_filename`, `old_filename` while `vsi_copy_file()` uses `src_file`, `target_file` (reversing source/destination).  This follows the calling signatures of the underlying API functions that they wrap. We didn't have to retain that for the package, but that was the choice made.  At least it should be consistent throughout for wrapper functions.

### CODE REVIEW

**Comment by ctoney** [comment]
@goergen95, I'm wondering about the default `show_progress=FALSE`. I'm kind of neutral but the context will often be larger files and network VSI, so maybe it should be changed to `TRUE` instead. Do you have a preference either way?

**Comment by goergen95** [comment]
I guess on a question like this you will always have as many opinions as there are people in the room. In my case, there would rarely be a single data set, so I would anyways have to implement progress report on a higher level. Personally, I'd be happy with the current setting of not reporting progress by default. One could try to make some assumptions on the primary audience for `gdalraster`, but in the end it will be a decision of who to disappoint. I've seen a nice article on [rOpenSci](https://ropensci.org/blog/2024/02/06/verbosity-control-packages/) touching on that topic, but I have to admit that I have yet to read it.

**Comment by goergen95** [comment]
I think I do not really understand what this means:
> any of the above or /vsicurl/ -> /vsiaz/ (starting with GDAL 3.8)

That is from GDAL docs, right? Do you have an idea what is meant here?

**Comment by ctoney** [comment]
Thanks, that is helpful. I will leave progress off by default in `vsi_copy_file()`. gdalraster  throughout has progress bars enabled, generally with no way to turn them off. I will address that at some point, but a little ways off unless something comes up that needs it.

re:
>any of the above or /vsicurl/ -> /vsiaz/ (starting with GDAL 3.8)

Yes that is copied from the GDAL docs. I think it means that if destination is Azure Blob, and source is any of vsis3, vsigs, vsiaz, vsiadls or vsicurl, then the copy is direct without going through the local computer (as of GDAL 3.8). I don't know how it is implemented in GDAL but there is a related API here:
https://learn.microsoft.com/en-us/rest/api/storageservices/put-block-from-url?tabs=microsoft-entra-id

Also, thanks for your comments on the issue you opened. Will follow up there soon.

**Pull request merged**
