### PR TITLE
`GDALVector::initDF_()`: create the data frame vectors with `Rcpp::no_init()`

### PR DESCRIPTION
**Pull request by ctoney**
We already iterate each element of the data frame in `GDALVector::fetch()`, so set `NA` values there and skip initialization when the vectors are created. Potential performance improvement when reading large result sets.

### CODE REVIEW

**Review by joshyam-k — APPROVED** [review]
Looks good and makes sense. I'm assuming `Rcpp::no_init` has well defined memory allocation behavior for `Rcpp::List` objects, but that one does seem more complex than the normal classed vector versions.

**Comment by ctoney** [comment]
Thanks. I wondered about that too. List is based on `VECSXP`, generic type that can point to any other vector type. Allocation would be for that pointer type. Assigning a list element to a value should just be updating the reference. `Rcpp::List` is default initialized to the `NULL` object unlike the other vector types which initialize to `0` or `""`.
```r
library(Rcpp)
test <- cppFunction(
    'void test_list_init() {
        List l = List(1);
        
        RObject r = l[0];
        Rcout << r << std::endl;
        if (r.isNULL())
            Rcout << true << std::endl;
        else
            Rcout << false << std::endl;
        
        l[0] = CharacterVector{"a string"};
        r = l[0];
        Rcout << r << std::endl;
        CharacterVector v(r);
        Rcout << v << std::endl;
    }')
    
test()
#> 0x5586815331a0
#> 1
#> 0x5586815b74c0
#> "a string"
```

**Comment by ctoney** [comment]
update: this PR did cause a problem though. Valgrind reports "Conditional jump or move depends on uninitialised value(s)" (https://github.com/USDAForestService/gdalraster/actions/runs/10864245923).

I'm not sure yet where that happens. Valgrind does not report any errors from running the test suite. The errors only happen when running the examples. There is a lot more usage of class GDALVector in the tests, but the tests are not complete yet so probably missing something there. I'm going to investigate more and try to replicate in the tests, before giving up on no_init.

**Comment by ctoney** [comment]
Fixed in #520. Nice when the problem code ends up being code you were thinking about removing anyway.

**Pull request merged**
