### PR TITLE
Add minimal S3 classing for `OGRFeature` and `OGRFeatureSet`

### PR DESCRIPTION
**Pull request by ctoney**
This PR adds S3 classes `OGRFeature` (`list` returned by `GDALVector::getFeature()` / `GDALVector::getNextFeature()`) and `OGRFeatureSet` (`data.frame` returned by `GDALVector::fetch()`). These carry  the attribute `gis` , a list of relevant attributes for vector data. The list elements are `character` vectors which will have length >1 if more than one geometry column is present. In that case, the first geometry column would be considered as default in class methods.

Rationale
A `GDALVector` object has the setting `$returnGeomAs` which defaults to `"WKB"`. This can be set to `"NONE"` which may be beneficial for performance and memory usage when access only to feature attributes is needed. But in general, `"WKB"` is the preferred default for performance in the typical case of feature data fetched with geometries. A `print()` method is desirable for readable display of the WKB `raw` vectors when a feature or feature set is printed to the console. Similar handling for display is provided for `$returnGeomAs` set to `"WKT"`.

This PR also adds package `wk` to Imports (previously in Suggests). A `plot()` method is provided for `OGRFeature` and `OGRFeatureSet`, simply plotting the geometries via `wk::wk_plot()`.

``` r
library(gdalraster)
#> GDAL 3.8.4, released 2024/02/08, GEOS 3.12.1, PROJ 9.3.1

dsn <- system.file("extdata/ynp_fires_1984_2022.gpkg", package = "gdalraster")
lyr <- new(GDALVector, dsn, "mtbs_perims")

lyr$setSelectedFields(c("incid_name", "ig_year", "OGR_GEOMETRY"))
lyr$setAttributeFilter("ig_year >= 2010")
lyr$getFeatureCount()
#> [1] 16

feat <- lyr$getNextFeature()
feat
#> OGR feature
#> $FID
#> integer64
#> [1] 46
#> 
#> $incid_name
#> [1] ANTELOPE
#> 
#> $ig_year
#> [1] 2010
#> 
#> $geom
#> [1] WKB MULTIPOLYGON: raw 01 06 00 00 ...

attr(feat, "gis")
#> $type
#> [1] "vector"
#> 
#> $geom_column
#> [1] "geom"
#> 
#> $geom_col_type
#> [1] "MULTIPOLYGON"
#> 
#> $geom_col_srs
#> [1] "PROJCS[\"NAD83 / Montana\",GEOGCS[\"NAD83\",DATUM[\"North_American_Datum_1983\",SPHEROID[\"GRS 1980\",6378137,298.257222101,AUTHORITY[\"EPSG\",\"7019\"]],AUTHORITY[\"EPSG\",\"6269\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4269\"]],PROJECTION[\"Lambert_Conformal_Conic_2SP\"],PARAMETER[\"latitude_of_origin\",44.25],PARAMETER[\"central_meridian\",-109.5],PARAMETER[\"standard_parallel_1\",49],PARAMETER[\"standard_parallel_2\",45],PARAMETER[\"false_easting\",600000],PARAMETER[\"false_northing\",0],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH],AUTHORITY[\"EPSG\",\"32100\"]]"
#> 
#> $geom_format
#> [1] "WKB"

plot(feat)
```

``` r

feat_set <- lyr$fetch(-1)
feat_set
#> OGR feature set
#>    FID              incid_name ig_year                                  geom
#> 1   46                ANTELOPE    2010 WKB MULTIPOLYGON: raw 01 06 00 00 ...
#> 2   47                  CYGNET    2012 WKB MULTIPOLYGON: raw 01 06 00 00 ...
#> 3   48                 DEWDROP    2012 WKB MULTIPOLYGON: raw 01 06 00 00 ...
#> 4   49                   POINT    2011 WKB MULTIPOLYGON: raw 01 06 00 00 ...
#> 5   50                    ALUM    2013 WKB MULTIPOLYGON: raw 01 06 00 00 ...
#> 6   51                   ALDER    2013 WKB MULTIPOLYGON: raw 01 06 00 00 ...
#> 7   52 FY13 YELL WFU INCIDENTS    2013 WKB MULTIPOLYGON: raw 01 06 00 00 ...
#> 8   53                  SPRUCE    2015 WKB MULTIPOLYGON: raw 01 06 00 00 ...
#> 9   54                 BUFFALO    2016 WKB MULTIPOLYGON: raw 01 06 00 00 ...
#> 10  55                   BERRY    2016 WKB MULTIPOLYGON: raw 01 06 00 00 ...
#> 11  56                   MAPLE    2016 WKB MULTIPOLYGON: raw 01 06 00 00 ...
#> 12  57                    FAWN    2016 WKB MULTIPOLYGON: raw 01 06 00 00 ...
#> 13  58                 CENTRAL    2016 WKB MULTIPOLYGON: raw 01 06 00 00 ...
#> 14  59              BACON RIND    2018 WKB MULTIPOLYGON: raw 01 06 00 00 ...
#> 15  60                FISHHAWK    2019 WKB MULTIPOLYGON: raw 01 06 00 00 ...
#> 16  61               LONE STAR    2020 WKB MULTIPOLYGON: raw 01 06 00 00 ...

plot(feat_set)
```

Documentation and code examples are updated for class `GDALVector`. Documentation for the setting  `GDALVector::returnGeomAs` is also modified to remove the options `"SUMMARY"` and `"TYPE_NAME"`. These are currently left in the code as undocumented options but may be changed or removed in the future. The functions `g_name()` and `g_summary()` operate on input of WKB raw vector or list of raw vectors, or WKT, provide the equivalent functionality
``` r
lyr$resetReading()

feat <- lyr$getNextFeature()
g_summary(feat$geom)
#> [1] "MULTIPOLYGON : 1 geometries: POLYGON : 64 points"

feat_set <- lyr$fetch(5)
g_summary(feat_set$geom)
#> [1] "MULTIPOLYGON : 1 geometries: POLYGON : 59 points"                                                         
#> [2] "MULTIPOLYGON : 4 geometries: POLYGON : 36 points POLYGON : 5 points POLYGON : 5 points POLYGON : 5 points"
#> [3] "MULTIPOLYGON : 1 geometries: POLYGON : 42 points"                                                         
#> [4] "MULTIPOLYGON : 2 geometries: POLYGON : 29 points POLYGON : 67 points"                                     
#> [5] "MULTIPOLYGON : 2 geometries: POLYGON : 5 points POLYGON : 44 points"

lyr$close()
```

<sup>Created on 2024-09-28 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by mdsumner** [comment]
Looks good!   I note that pre GDAL 3.7.0 if you set "SUMMARY" you get "TYPE_NAME". 

I also find it a bit funny to get a classed geom OR a character string, depending on `returnGeomAs` - like it's a bit off-putting seeing a classed print "WKB/T MULTIPOLYGON: ..." vs "MULTIPOLYGON", but at least the former is unquoted, and I don't have a better suggestion anyway. 

A feature request: add "BBOX" for `returnGeomAs` and just return the `c(xmin, ymin, xmax, ymax)` values (I will want that for gutting vapour when I get to it, so leave that as a PR task for me if you like). 

I split off #539 which I discovered doing testing but isn't about this PR.

**Review by mdsumner — APPROVED** [review]
lgtm

**Comment by ctoney** [comment]
This PR also fixes #539 which is not specifically related but was discovered while testing the S3 methods, and the fix was in code coincident with attaching gis attributes.

**Comment by ctoney** [comment]
@mdsumner, "BBOX" option for `returnGeomAs` makes sense. A PR is welcome but no worries if you don't get to it. I'll circle back at some point either way, and check with you before I do anything. Thanks for the review and bug report!

**Comment by mdsumner** [comment]
awesome, I'm focussed on some legacy stuff atm that needs terra but it will eventually get abstracted sideways by using gdalraster!    You've already covered most of the vapour-support for vector here, which is fabulous for me, thanks!!

**Pull request merged**
